export const CREATE_APPLICATION_STARTED = 'CREATE_APPLICATION_STARTED';
export const CREATE_APPLICATION_SUCCESS = 'CREATE_APPLICATION_SUCCESS';
export const CREATE_APPLICATION_FAILURE = 'CREATE_APPLICATION_FAILURE';
