export const CREATE_OFFER_STARTED = 'CREATE_OFFER_STARTED';
export const CREATE_OFFER_SUCCESS = 'CREATE_OFFER_SUCCESS';
export const CREATE_OFFER_FAILURE = 'CREATE_OFFER_FAILURE';
export const GET_OFFER_STARTED = 'GET_OFFER_STARTED';
export const GET_OFFER_SUCCESS = 'GET_OFFER_SUCCESS';
export const GET_OFFER_FAILURE = 'GET_OFFER_FAILURE';
