export const GET_PROJECT_STARTED = 'GET_PROJECT_STARTED ';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS ';
export const GET_PROJECT_FAILURE = 'GET_PROJECT_FAILURE ';
export const CREATE_PROJECT_STARTED = 'CREATE_PROJECT_STARTED';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';
