export const SIGN_USER_STARTED = 'SIGN_USER_STARTED';
export const SIGN_USER_SUCCESS = 'SIGN_USER_SUCCESS';
export const SIGN_USER_FAILURE = 'SIGN_USER_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
