export const USER_LOGOUT = 'USER_LOGOUT';
export const SIGN_USER_STARTED = 'SIGN_USER_STARTED';
export const SIGN_USER_SUCCESS = 'SIGN_USER_SUCCESS';
export const SIGN_USER_FAILURE = 'SIGN_USER_FAILURE';
export const INVITE_USER_STARTED = 'INVITE_USER_STARTED';
export const INVITE_USER_SUCCESS = 'INVITE_USER_SUCCESS';
export const INVITE_USER_FAILURE = 'INVITE_USER_FAILURE';
